=== lastaflute/lasta-di/src/main/resources/org/lastaflute/di/lastadi10.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE components PUBLIC "-//DBFLUTE//DTD LastaDi 1.0//EN" 
	"http://dbflute.org/meta/lastadi10.dtd">
-->
<!ELEMENT components (
        description?,
        include*,
        (component | meta | xi:include)*
)>

<!ATTLIST components namespace CDATA #IMPLIED>
<!ATTLIST components initializeOnCreate (true | false) "false">
<!ATTLIST components xmlns:xi  CDATA #FIXED "http://www.w3.org/2001/XInclude">

<!ELEMENT description (
        #PCDATA
)>

<!ELEMENT include EMPTY>
<!ATTLIST include path CDATA #REQUIRED>
<!ATTLIST include condition CDATA #IMPLIED>


<!ELEMENT component (
  #PCDATA | description | arg | property | meta |
            postConstruct | preDestroy | aspect | interType)*>
<!ATTLIST component instance (
  singleton | prototype | outer | request | session | application) "singleton">
<!ATTLIST component class CDATA #IMPLIED>
<!ATTLIST component name CDATA #IMPLIED>
<!ATTLIST component autoBinding (auto | constructor | property | semiauto | none) "auto">
<!ATTLIST component externalBinding (true | false) "false">

<!ELEMENT arg (
        #PCDATA | description | component | meta
)*>

<!ELEMENT property (
        #PCDATA | description | component | meta
)*>

<!ATTLIST property name CDATA #REQUIRED>

<!ATTLIST property bindingType (must | should | may | none) "should">

<!ELEMENT aspect (
        #PCDATA | description | component)*>
<!ATTLIST aspect pointcut CDATA #IMPLIED>

<!ELEMENT interType (
		#PCDATA | description | component)*>

<!ELEMENT postConstruct (
        #PCDATA | description | arg
)*>
<!ATTLIST postConstruct name CDATA #IMPLIED>

<!ELEMENT preDestroy (
        #PCDATA | description | arg
)*>
<!ATTLIST preDestroy name CDATA #IMPLIED>

<!ELEMENT meta (
        #PCDATA | description | component | meta
)*>

<!ATTLIST meta name CDATA #IMPLIED>

<!ELEMENT xi:include (xi:fallback?)>
<!ATTLIST xi:include
    xmlns:xi        CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
    href            CDATA       #IMPLIED
    parse           (xml|text)  "xml"
    xpointer        CDATA       #IMPLIED
    encoding        CDATA       #IMPLIED
    accept          CDATA       #IMPLIED
    accept-language CDATA       #IMPLIED
>

<!ELEMENT xi:fallback ANY>
<!ATTLIST xi:fallback
    xmlns:xi   CDATA   #FIXED   "http://www.w3.org/2001/XInclude"
>

=== lastaflute/lasta-di/src/main/resources/smart/warmdeploy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//DBFLUTE//DTD LastaDi 1.0//EN" 
	"http://dbflute.org/meta/lastadi10.dtd">
<components>
	<include path="convention.xml"/>
	<include path="creator.xml"/>
	<include path="customizer.xml"/>

	<component class="org.dbflute.lasta.di.core.smart.warm.WarmdeployBehavior"/>
	
	<component name="defaultBuilder" class="org.dbflute.lasta.di.core.factory.dixml.DiXmlLaContainerBuilder">
		<property name="rule">
			<component class="org.dbflute.lasta.di.core.factory.dixml.DiXmlTagHandlerRule">
				<postConstruct name="addTagHandler">
					<arg>"/components"</arg>
					<arg>
						<component class="org.dbflute.lasta.di.core.factory.dixml.taghandler.ComponentsTagHandler">
							<!-- parsed by plain hook as type expression using at-mark -->
							<property name="containerImplClass">
								@org.dbflute.lasta.di.core.meta.impl.ThreadSafeLaContainerImpl@class
							</property>
						</component>
					</arg>
				</postConstruct>
			</component>
		</property>
	</component>
</components>

=== lastaflute/lasta-di/src/main/resources/tx_customizer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//DBFLUTE//DTD LastaDi 1.0//EN" 
	"http://dbflute.org/meta/lastadi10.dtd">
<components>
	<component name="requiredTxCustomizer" class="org.lastaflute.di.core.customizer.AspectCustomizer">
		<property name="interceptorName">"tx_aop.requiredTx"</property>
	</component>
	<component name="requiresNewTxCustomizer" class="org.lastaflute.di.core.customizer.AspectCustomizer">
		<property name="interceptorName">"tx_aop.requiresNewTx"</property>
	</component>
	<component name="mandatoryTxCustomizer" class="org.lastaflute.di.core.customizer.AspectCustomizer">
		<property name="interceptorName">"tx_aop.mandatoryTx"</property>
	</component>
	<component name="notSupportedTxCustomizer" class="org.lastaflute.di.core.customizer.AspectCustomizer">
		<property name="interceptorName">"tx_aop.notSupportedTx"</property>
	</component>
	<component name="neverTxCustomizer" class="org.lastaflute.di.core.customizer.AspectCustomizer">
		<property name="interceptorName">"tx_aop.neverTx"</property>
	</component>
</components>

=== lastaflute/lasta-di/src/main/resources/embedded_customizer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//DBFLUTE//DTD LastaDi 1.0//EN" 
	"http://dbflute.org/meta/lastadi10.dtd">
<components>
	<include path="tx_customizer.xml"/>

	<component name="actionCustomizer" class="org.dbflute.lasta.di.core.customizer.ext.ConcreteDrivenCustomizerChain">
	</component>
	<component name="assistCustomizer" class="org.dbflute.lasta.di.core.customizer.ext.ConcreteDrivenCustomizerChain">
	</component>
	<component name="logicCustomizer" class="org.dbflute.lasta.di.core.customizer.ext.ConcreteDrivenCustomizerChain">
	  	<postConstruct name="addCustomizer">
			<arg>
				<component class="org.dbflute.lasta.di.core.customizer.ext.ExplicitTxAttributeCustomizer"/>
			</arg>
	  	</postConstruct>
	</component>
	<component name="serviceCustomizer" class="org.dbflute.lasta.di.core.customizer.ext.ConcreteDrivenCustomizerChain">
	  	<postConstruct name="addCustomizer">
			<arg>
				<component class="org.dbflute.lasta.di.core.customizer.ext.ExplicitTxAttributeCustomizer"/>
			</arg>
	  	</postConstruct>
	</component>
	<component name="helperCustomizer" class="org.dbflute.lasta.di.core.customizer.ext.ConcreteDrivenCustomizerChain">
	</component>
	<component name="validatorCustomizer" class="org.dbflute.lasta.di.core.customizer.ext.ConcreteDrivenCustomizerChain">
	</component>
	<component name="converterCustomizer" class="org.dbflute.lasta.di.core.customizer.ext.ConcreteDrivenCustomizerChain">
	</component>
	<component name="interceptorCustomizer" class="org.dbflute.lasta.di.core.customizer.ext.ConcreteDrivenCustomizerChain">
	</component>
</components>

=== lastaflute/lasta-di/src/main/resources/embedded_creator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//DBFLUTE//DTD LastaDi 1.0//EN"
	"http://dbflute.org/meta/lastadi10.dtd">
<components>
	<include path="convention.xml"/>
	<include path="customizer.xml"/>

	<component name="actionCreator" class="org.dbflute.lasta.di.core.creator.ActionCreator"/>
	<component name="assistCreator" class="org.dbflute.lasta.di.core.creator.AssistCreator"/>
	<component name="logicCreator" class="org.dbflute.lasta.di.core.creator.LogicCreator"/>
	<component name="serviceCreator" class="org.dbflute.lasta.di.core.creator.ServiceCreator"/>
	<component name="helperCreator" class="org.dbflute.lasta.di.core.creator.HelperCreator"/>
	<component name="interceptorCreator" class="org.dbflute.lasta.di.core.creator.InterceptorCreator"/>
</components>
